CREATE TABLE MOVIEAWARDCATESUBGORYRESULTS(
		ID INT IDENTITY(1,1),
		RESULTNAMECode VARCHAR(3),
		RESULTNAME VARCHAR(25)
	)
GO;

INSERT INTO MOVIEAWARDCATESUBGORYRESULTS VALUES( 'NOM', 'Nominated');
GO;
INSERT INTO MOVIEAWARDCATESUBGORYRESULTS VALUES( 'WON', 'Won');
GO;