CREATE TABLE AWARDS(
		ID INT IDENTITY(1,1),
		AWARDNAME VARCHAR(100),
		AWARDTYPE_FK INT,
		AWARDCOUNTRY VARCHAR(100),
		AWARDDESCRIPTION VARCHAR(1000), 
    CONSTRAINT [PK_AWARDS] PRIMARY KEY ([ID])
	)