CREATE TABLE MOVIEAWARDCATEGORY(
		ID INT IDENTITY(1,1),
		AWARDCATEGORY VARCHAR(100),
		RECEIPIENTS_NOMINIEES VARCHAR(500),
		AWARDCATEGORYRESULTS__FK INT, 
    CONSTRAINT [PK_MOVIEAWARDCATEGORY] PRIMARY KEY ([ID])
	)