CREATE TABLE PRODUCERS (
		ID INT IDENTITY(1,1),
		PRODUCERNAME VARCHAR(100), 
		[PRODUCERDESCRIPTION] VARCHAR(1000) NULL, 
		[PRODUCERDOB] DATE NULL, 
		[NATIONALITY] VARCHAR(50) NULL, 
		[YEARACTIVESTART] INT NULL, 
		[YEARACTIVEEND] INT NULL, 
    CONSTRAINT [PK_PRODUCERS] PRIMARY KEY ([ID])
	)